\section{Thread\-Synch::Unexpected\-Exception Class Reference}
\label{class_thread_synch_1_1_unexpected_exception}\index{ThreadSynch::UnexpectedException@{ThreadSynch::UnexpectedException}}
thrown when a scheduled call throws an exception which wasn't expected by the user.  


{\tt \#include $<$Call\-Scheduler\-Exceptions.h$>$}

\subsection*{Public Member Functions}
\begin{CompactItemize}
\item 
{\bf Unexpected\-Exception} ()
\end{CompactItemize}


\subsection{Detailed Description}
thrown when a scheduled call throws an exception which wasn't expected by the user. 



\subsection{Constructor \& Destructor Documentation}
\index{ThreadSynch::UnexpectedException@{Thread\-Synch::Unexpected\-Exception}!UnexpectedException@{UnexpectedException}}
\index{UnexpectedException@{UnexpectedException}!ThreadSynch::UnexpectedException@{Thread\-Synch::Unexpected\-Exception}}
\subsubsection{\setlength{\rightskip}{0pt plus 5cm}Thread\-Synch::Unexpected\-Exception::Unexpected\-Exception ()\hspace{0.3cm}{\tt  [inline]}}\label{class_thread_synch_1_1_unexpected_exception_98601b3ba5bc4a26ee92713e386744ee}




The documentation for this class was generated from the following file:\begin{CompactItemize}
\item 
Thread\-Synch/{\bf Call\-Scheduler\-Exceptions.h}\end{CompactItemize}
